-- GENERATED by apps/solara/tools/seed_d1_cities.py — Stella 相談 候補プール (D1)
-- Cloudflare D1 schema. 適用:
--   wrangler d1 execute solara-cities --remote --file=apps/solara/worker/migrations/0001_cities.sql
DROP TABLE IF EXISTS cities;
CREATE TABLE cities (
  id         INTEGER PRIMARY KEY,   -- GeoNames geonameid
  name       TEXT NOT NULL,         -- 日本語表示名 (無ければローマ字)
  ascii      TEXT,                  -- asciiname (ローマ字フォールバック / 検索用)
  lat        REAL NOT NULL,
  lng        REAL NOT NULL,
  country    TEXT NOT NULL,         -- ISO 3166-1 alpha-2
  region     TEXT,                  -- 日本語県名 (JP のみ)、他は NULL
  population INTEGER NOT NULL DEFAULT 0
);
-- bounding-box (おでかけ/近傍半径): lat 範囲で絞り lng でフィルタ
CREATE INDEX idx_cities_latlng ON cities(lat, lng);
-- 自国スコープ: WHERE country=? AND population>=? ORDER BY population DESC
CREATE INDEX idx_cities_country_pop ON cities(country, population);
-- 世界/地域スコープ: population フロア + ORDER BY population DESC LIMIT N
CREATE INDEX idx_cities_pop ON cities(population);
